# Generated by Django 4.2.5 on 2023-09-25 20:09

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_document_original_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        null=True, upload_to=chat.models.user_directory_path
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("num_words", models.IntegerField(default=0)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.chat"
                    ),
                ),
            ],
        ),
    ]
