# Generated by Django 4.2.4 on 2023-12-02 16:29

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='mean_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='summary_embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='model_name',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5-Turbo (default ChatGPT model)')], default='gpt-3.5-turbo', max_length=255),
        ),
    ]
